title: Sneh Namdeo # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 System Enginner
  <br><br>
  <a href="mailto:er.snamdeo@gmail.com">er.snamdeo@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/sneh-namdeo-607803b2/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/SnehNamdeo/">Github</a> 
theme: jekyll-theme-minimal
